sudo: required
services:
 - docker

before_install:
- docker build -f dockerfile.dev -t kwn2019/docker-react .

script:
 - docker run -e CI=true kwn2019/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-west-2"
 app: "dock-react"
 env: "DockReact-env"
 bucket_name: "elasticbeanstalk-us-west-2-141078446921"
 bucket_path: "dock-react"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"