FROM node:latest
# Folder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH "/usr/src/app/node_modules/.bin:$PATH"
ADD package.json /usr/src/app/package.json
RUN npm install
ADD . /usr/src/app
CMD ["npm","run","start"]