version: '3'
services:
 start:
  build:
   context: .
   dockerfile: dockerfile.dev
  ports:
   - "3000:3000"
  volumes:
   - "/usr/src/app/node_modules"
   - ".:/usr/src/app"
 test:
  build:
   context: .
   dockerfile: dockerfile.dev
  volumes:
   - "/usr/src/app/node_modules"
   - ".:/usr/src/app"
  command: ["npm","run","test"]